import type { Product } from "./product";
import type { Product } from "./product";

export const defaultProducts: Product[] = [
  {
    id: 1,
    name: "Châteauneuf-du-Pape",
    description:
      "A bold, complex red wine with notes of dark fruit, spice, and herbs.",
    price: 49.99,
    pictureUrl: "/images/chateauneuf.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 20,
  },
  {
    id: 2,
    name: "Gigondas",
    description: "Rich and powerful with deep cherry and pepper flavors.",
    price: 34.99,
    pictureUrl: "/images/gigondas.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 15,
  },
  {
    id: 3,
    name: "Vacqueyras",
    description: "Elegant and full-bodied, blending Grenache and Syrah grapes.",
    price: 29.99,
    pictureUrl: "/images/vacqueyras.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 18,
  },
  {
    id: 4,
    name: "Rasteau",
    description:
      "Dry and intense, known for its bold tannins and ripe fruit profile.",
    price: 27.99,
    pictureUrl: "/images/rasteau.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 12,
  },
  {
    id: 5,
    name: "Beaumes-de-Venise (Red)",
    description: "Smooth and velvety, distinct from its sweet Muscat cousin.",
    price: 25.99,
    pictureUrl: "/images/beaumes.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 10,
  },
  {
    id: 6,
    name: "Vinsobres",
    description: "Spicy and structured with good aging potential.",
    price: 23.99,
    pictureUrl: "/images/vinsobres.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 14,
  },
  {
    id: 7,
    name: "Cairanne",
    description: "Balanced and aromatic, with red berry and herbal notes.",
    price: 22.99,
    pictureUrl: "/images/cairanne.jpg",
    type: "Red Wine",
    brand: "Rhône Valley",
    quantityInStock: 16,
  },
];
